// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_products-upload_product_image
 */
export type Body_products_upload_product_image = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Alt Text
     */
    alt_text?: string | null;
};

/**
 * BrandCreate
 */
export type BrandCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * BrandPublic
 */
export type BrandPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * BrandUpdate
 */
export type BrandUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * BrandsPublic
 */
export type BrandsPublic = {
    /**
     * Data
     */
    data: Array<BrandPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoriesPublic
 */
export type CategoriesPublic = {
    /**
     * Data
     */
    data: Array<CategoryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CategoryCreate
 */
export type CategoryCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * CategoryPublic
 */
export type CategoryPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CategoryUpdate
 */
export type CategoryUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PermissionPublic
 */
export type PermissionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Code
     */
    code: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Sku
     */
    sku: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Brand Id
     */
    brand_id?: string | null;
    /**
     * Product Type
     */
    product_type?: string | null;
    /**
     * Material
     */
    material?: string | null;
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Usage Area
     */
    usage_area?: string | null;
    /**
     * Color Family
     */
    color_family?: string | null;
    /**
     * Width Mm
     */
    width_mm?: number | null;
    /**
     * Height Mm
     */
    height_mm?: number | null;
    /**
     * Thickness Mm
     */
    thickness_mm?: number | null;
    /**
     * Rectified
     */
    rectified?: boolean;
    /**
     * Anti Slip Rating
     */
    anti_slip_rating?: string | null;
    /**
     * Water Absorption Percent
     */
    water_absorption_percent?: number | string | null;
    /**
     * Pieces Per Box
     */
    pieces_per_box?: number | null;
    /**
     * Sqm Per Box
     */
    sqm_per_box?: number | string | null;
    /**
     * Kg Per Box
     */
    kg_per_box?: number | string | null;
    /**
     * Country Of Origin
     */
    country_of_origin?: string | null;
    /**
     * Price
     */
    price?: number | string | null;
    /**
     * Stock Quantity
     */
    stock_quantity?: number;
    /**
     * Low Stock Threshold
     */
    low_stock_threshold?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Featured
     */
    is_featured?: boolean;
};

/**
 * ProductImageOrder
 */
export type ProductImageOrder = {
    /**
     * Image Ids
     */
    image_ids: Array<string>;
};

/**
 * ProductImagePublic
 */
export type ProductImagePublic = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Storage Key
     */
    storage_key: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Alt Text
     */
    alt_text?: string | null;
    /**
     * Sort Order
     */
    sort_order?: number;
    /**
     * Is Primary
     */
    is_primary?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ProductImagesPublic
 */
export type ProductImagesPublic = {
    /**
     * Data
     */
    data: Array<ProductImagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Sku
     */
    sku: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category Id
     */
    category_id: string;
    /**
     * Brand Id
     */
    brand_id?: string | null;
    /**
     * Product Type
     */
    product_type?: string | null;
    /**
     * Material
     */
    material?: string | null;
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Usage Area
     */
    usage_area?: string | null;
    /**
     * Color Family
     */
    color_family?: string | null;
    /**
     * Width Mm
     */
    width_mm?: number | null;
    /**
     * Height Mm
     */
    height_mm?: number | null;
    /**
     * Thickness Mm
     */
    thickness_mm?: number | null;
    /**
     * Rectified
     */
    rectified?: boolean;
    /**
     * Anti Slip Rating
     */
    anti_slip_rating?: string | null;
    /**
     * Water Absorption Percent
     */
    water_absorption_percent?: string | null;
    /**
     * Pieces Per Box
     */
    pieces_per_box?: number | null;
    /**
     * Sqm Per Box
     */
    sqm_per_box?: string | null;
    /**
     * Kg Per Box
     */
    kg_per_box?: string | null;
    /**
     * Country Of Origin
     */
    country_of_origin?: string | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Stock Quantity
     */
    stock_quantity?: number;
    /**
     * Low Stock Threshold
     */
    low_stock_threshold?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Featured
     */
    is_featured?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Stock State
     */
    stock_state: string;
    /**
     * Images
     */
    images?: Array<ProductImagePublic>;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Sku
     */
    sku?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category Id
     */
    category_id?: string | null;
    /**
     * Brand Id
     */
    brand_id?: string | null;
    /**
     * Product Type
     */
    product_type?: string | null;
    /**
     * Material
     */
    material?: string | null;
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Usage Area
     */
    usage_area?: string | null;
    /**
     * Color Family
     */
    color_family?: string | null;
    /**
     * Width Mm
     */
    width_mm?: number | null;
    /**
     * Height Mm
     */
    height_mm?: number | null;
    /**
     * Thickness Mm
     */
    thickness_mm?: number | null;
    /**
     * Rectified
     */
    rectified?: boolean | null;
    /**
     * Anti Slip Rating
     */
    anti_slip_rating?: string | null;
    /**
     * Water Absorption Percent
     */
    water_absorption_percent?: number | string | null;
    /**
     * Pieces Per Box
     */
    pieces_per_box?: number | null;
    /**
     * Sqm Per Box
     */
    sqm_per_box?: number | string | null;
    /**
     * Kg Per Box
     */
    kg_per_box?: number | string | null;
    /**
     * Country Of Origin
     */
    country_of_origin?: string | null;
    /**
     * Price
     */
    price?: number | string | null;
    /**
     * Stock Quantity
     */
    stock_quantity?: number | null;
    /**
     * Low Stock Threshold
     */
    low_stock_threshold?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Featured
     */
    is_featured?: boolean | null;
};

/**
 * ProductsPublic
 */
export type ProductsPublic = {
    /**
     * Data
     */
    data: Array<ProductPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RoleAssignment
 */
export type RoleAssignment = {
    /**
     * Role Id
     */
    role_id: string;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Slug
     */
    slug?: string | null;
    /**
     * Permissions
     */
    permissions?: Array<string>;
};

/**
 * RolePublic
 */
export type RolePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Is System
     */
    is_system: boolean;
    /**
     * Permissions
     */
    permissions?: Array<PermissionPublic>;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * RoleSummary
 */
export type RoleSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Is System
     */
    is_system: boolean;
};

/**
 * RoleUpdate
 */
export type RoleUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Permissions
     */
    permissions?: Array<string> | null;
};

/**
 * RolesPublic
 */
export type RolesPublic = {
    /**
     * Data
     */
    data: Array<RolePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Locale
     */
    locale?: string;
    /**
     * Password
     */
    password: string;
    /**
     * Role Id
     */
    role_id?: string | null;
};

/**
 * UserMePublic
 */
export type UserMePublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Locale
     */
    locale?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    role?: RoleSummary | null;
    /**
     * Permissions
     */
    permissions?: Array<string>;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Locale
     */
    locale?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    role?: RoleSummary | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Locale
     */
    locale?: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserMePublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type usersAssignUserRoleData = {
    body: RoleAssignment;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}/role';
};

export type usersAssignUserRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersAssignUserRoleError = usersAssignUserRoleErrors[keyof usersAssignUserRoleErrors];

export type usersAssignUserRoleResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersAssignUserRoleResponse = usersAssignUserRoleResponses[keyof usersAssignUserRoleResponses];

export type rolesReadRolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/roles/';
};

export type rolesReadRolesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type rolesReadRolesError = rolesReadRolesErrors[keyof rolesReadRolesErrors];

export type rolesReadRolesResponses = {
    /**
     * Successful Response
     */
    200: RolesPublic;
};

export type rolesReadRolesResponse = rolesReadRolesResponses[keyof rolesReadRolesResponses];

export type rolesCreateRoleData = {
    body: RoleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/roles/';
};

export type rolesCreateRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type rolesCreateRoleError = rolesCreateRoleErrors[keyof rolesCreateRoleErrors];

export type rolesCreateRoleResponses = {
    /**
     * Successful Response
     */
    201: RolePublic;
};

export type rolesCreateRoleResponse = rolesCreateRoleResponses[keyof rolesCreateRoleResponses];

export type rolesReadPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/roles/permissions';
};

export type rolesReadPermissionsResponses = {
    /**
     * Response Roles-Read Permissions
     *
     * Successful Response
     */
    200: Array<PermissionPublic>;
};

export type rolesReadPermissionsResponse = rolesReadPermissionsResponses[keyof rolesReadPermissionsResponses];

export type rolesDeleteRoleData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type rolesDeleteRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type rolesDeleteRoleError = rolesDeleteRoleErrors[keyof rolesDeleteRoleErrors];

export type rolesDeleteRoleResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type rolesDeleteRoleResponse = rolesDeleteRoleResponses[keyof rolesDeleteRoleResponses];

export type rolesReadRoleData = {
    body?: never;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type rolesReadRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type rolesReadRoleError = rolesReadRoleErrors[keyof rolesReadRoleErrors];

export type rolesReadRoleResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type rolesReadRoleResponse = rolesReadRoleResponses[keyof rolesReadRoleResponses];

export type rolesUpdateRoleData = {
    body: RoleUpdate;
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/v1/roles/{role_id}';
};

export type rolesUpdateRoleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type rolesUpdateRoleError = rolesUpdateRoleErrors[keyof rolesUpdateRoleErrors];

export type rolesUpdateRoleResponses = {
    /**
     * Successful Response
     */
    200: RolePublic;
};

export type rolesUpdateRoleResponse = rolesUpdateRoleResponses[keyof rolesUpdateRoleResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type itemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type itemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemsError = itemsReadItemsErrors[keyof itemsReadItemsErrors];

export type itemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type itemsReadItemsResponse = itemsReadItemsResponses[keyof itemsReadItemsResponses];

export type itemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type itemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsCreateItemError = itemsCreateItemErrors[keyof itemsCreateItemErrors];

export type itemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsCreateItemResponse = itemsCreateItemResponses[keyof itemsCreateItemResponses];

export type itemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsDeleteItemError = itemsDeleteItemErrors[keyof itemsDeleteItemErrors];

export type itemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type itemsDeleteItemResponse = itemsDeleteItemResponses[keyof itemsDeleteItemResponses];

export type itemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsReadItemError = itemsReadItemErrors[keyof itemsReadItemErrors];

export type itemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsReadItemResponse = itemsReadItemResponses[keyof itemsReadItemResponses];

export type itemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type itemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type itemsUpdateItemError = itemsUpdateItemErrors[keyof itemsUpdateItemErrors];

export type itemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type itemsUpdateItemResponse = itemsUpdateItemResponses[keyof itemsUpdateItemResponses];

export type categoriesReadCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/categories/';
};

export type categoriesReadCategoriesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type categoriesReadCategoriesError = categoriesReadCategoriesErrors[keyof categoriesReadCategoriesErrors];

export type categoriesReadCategoriesResponses = {
    /**
     * Successful Response
     */
    200: CategoriesPublic;
};

export type categoriesReadCategoriesResponse = categoriesReadCategoriesResponses[keyof categoriesReadCategoriesResponses];

export type categoriesCreateCategoryData = {
    body: CategoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/categories/';
};

export type categoriesCreateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type categoriesCreateCategoryError = categoriesCreateCategoryErrors[keyof categoriesCreateCategoryErrors];

export type categoriesCreateCategoryResponses = {
    /**
     * Successful Response
     */
    201: CategoryPublic;
};

export type categoriesCreateCategoryResponse = categoriesCreateCategoryResponses[keyof categoriesCreateCategoryResponses];

export type categoriesDeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type categoriesDeleteCategoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type categoriesDeleteCategoryError = categoriesDeleteCategoryErrors[keyof categoriesDeleteCategoryErrors];

export type categoriesDeleteCategoryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type categoriesDeleteCategoryResponse = categoriesDeleteCategoryResponses[keyof categoriesDeleteCategoryResponses];

export type categoriesReadCategoryData = {
    body?: never;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type categoriesReadCategoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type categoriesReadCategoryError = categoriesReadCategoryErrors[keyof categoriesReadCategoryErrors];

export type categoriesReadCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type categoriesReadCategoryResponse = categoriesReadCategoryResponses[keyof categoriesReadCategoryResponses];

export type categoriesUpdateCategoryData = {
    body: CategoryUpdate;
    path: {
        /**
         * Category Id
         */
        category_id: string;
    };
    query?: never;
    url: '/api/v1/categories/{category_id}';
};

export type categoriesUpdateCategoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type categoriesUpdateCategoryError = categoriesUpdateCategoryErrors[keyof categoriesUpdateCategoryErrors];

export type categoriesUpdateCategoryResponses = {
    /**
     * Successful Response
     */
    200: CategoryPublic;
};

export type categoriesUpdateCategoryResponse = categoriesUpdateCategoryResponses[keyof categoriesUpdateCategoryResponses];

export type brandsReadBrandsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/brands/';
};

export type brandsReadBrandsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type brandsReadBrandsError = brandsReadBrandsErrors[keyof brandsReadBrandsErrors];

export type brandsReadBrandsResponses = {
    /**
     * Successful Response
     */
    200: BrandsPublic;
};

export type brandsReadBrandsResponse = brandsReadBrandsResponses[keyof brandsReadBrandsResponses];

export type brandsCreateBrandData = {
    body: BrandCreate;
    path?: never;
    query?: never;
    url: '/api/v1/brands/';
};

export type brandsCreateBrandErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type brandsCreateBrandError = brandsCreateBrandErrors[keyof brandsCreateBrandErrors];

export type brandsCreateBrandResponses = {
    /**
     * Successful Response
     */
    201: BrandPublic;
};

export type brandsCreateBrandResponse = brandsCreateBrandResponses[keyof brandsCreateBrandResponses];

export type brandsDeleteBrandData = {
    body?: never;
    path: {
        /**
         * Brand Id
         */
        brand_id: string;
    };
    query?: never;
    url: '/api/v1/brands/{brand_id}';
};

export type brandsDeleteBrandErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type brandsDeleteBrandError = brandsDeleteBrandErrors[keyof brandsDeleteBrandErrors];

export type brandsDeleteBrandResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type brandsDeleteBrandResponse = brandsDeleteBrandResponses[keyof brandsDeleteBrandResponses];

export type brandsReadBrandData = {
    body?: never;
    path: {
        /**
         * Brand Id
         */
        brand_id: string;
    };
    query?: never;
    url: '/api/v1/brands/{brand_id}';
};

export type brandsReadBrandErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type brandsReadBrandError = brandsReadBrandErrors[keyof brandsReadBrandErrors];

export type brandsReadBrandResponses = {
    /**
     * Successful Response
     */
    200: BrandPublic;
};

export type brandsReadBrandResponse = brandsReadBrandResponses[keyof brandsReadBrandResponses];

export type brandsUpdateBrandData = {
    body: BrandUpdate;
    path: {
        /**
         * Brand Id
         */
        brand_id: string;
    };
    query?: never;
    url: '/api/v1/brands/{brand_id}';
};

export type brandsUpdateBrandErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type brandsUpdateBrandError = brandsUpdateBrandErrors[keyof brandsUpdateBrandErrors];

export type brandsUpdateBrandResponses = {
    /**
     * Successful Response
     */
    200: BrandPublic;
};

export type brandsUpdateBrandResponse = brandsUpdateBrandResponses[keyof brandsUpdateBrandResponses];

export type productsReadProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Q
         */
        q?: string | null;
        /**
         * Category Id
         */
        category_id?: string | null;
        /**
         * Brand Id
         */
        brand_id?: string | null;
        /**
         * Product Type
         */
        product_type?: string | null;
        /**
         * Material
         */
        material?: string | null;
        /**
         * Finish
         */
        finish?: string | null;
        /**
         * Usage Area
         */
        usage_area?: string | null;
        /**
         * Color Family
         */
        color_family?: string | null;
        /**
         * Width Mm
         */
        width_mm?: number | null;
        /**
         * Height Mm
         */
        height_mm?: number | null;
        /**
         * Thickness Mm
         */
        thickness_mm?: number | null;
        /**
         * Min Price
         */
        min_price?: number | string | null;
        /**
         * Max Price
         */
        max_price?: number | string | null;
        /**
         * Stock State
         */
        stock_state?: 'in_stock' | 'low_stock' | 'out_of_stock' | null;
        /**
         * Is Active
         */
        is_active?: boolean | null;
        /**
         * Is Featured
         */
        is_featured?: boolean | null;
    };
    url: '/api/v1/products/';
};

export type productsReadProductsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsReadProductsError = productsReadProductsErrors[keyof productsReadProductsErrors];

export type productsReadProductsResponses = {
    /**
     * Successful Response
     */
    200: ProductsPublic;
};

export type productsReadProductsResponse = productsReadProductsResponses[keyof productsReadProductsResponses];

export type productsCreateProductData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/api/v1/products/';
};

export type productsCreateProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsCreateProductError = productsCreateProductErrors[keyof productsCreateProductErrors];

export type productsCreateProductResponses = {
    /**
     * Successful Response
     */
    201: ProductPublic;
};

export type productsCreateProductResponse = productsCreateProductResponses[keyof productsCreateProductResponses];

export type productsDeleteProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsDeleteProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsDeleteProductError = productsDeleteProductErrors[keyof productsDeleteProductErrors];

export type productsDeleteProductResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type productsDeleteProductResponse = productsDeleteProductResponses[keyof productsDeleteProductResponses];

export type productsReadProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsReadProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsReadProductError = productsReadProductErrors[keyof productsReadProductErrors];

export type productsReadProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type productsReadProductResponse = productsReadProductResponses[keyof productsReadProductResponses];

export type productsUpdateProductData = {
    body: ProductUpdate;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsUpdateProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsUpdateProductError = productsUpdateProductErrors[keyof productsUpdateProductErrors];

export type productsUpdateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type productsUpdateProductResponse = productsUpdateProductResponses[keyof productsUpdateProductResponses];

export type productsDeactivateProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}/deactivate';
};

export type productsDeactivateProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsDeactivateProductError = productsDeactivateProductErrors[keyof productsDeactivateProductErrors];

export type productsDeactivateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type productsDeactivateProductResponse = productsDeactivateProductResponses[keyof productsDeactivateProductResponses];

export type productsUploadProductImageData = {
    body: Body_products_upload_product_image;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}/images/';
};

export type productsUploadProductImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsUploadProductImageError = productsUploadProductImageErrors[keyof productsUploadProductImageErrors];

export type productsUploadProductImageResponses = {
    /**
     * Successful Response
     */
    201: ProductImagePublic;
};

export type productsUploadProductImageResponse = productsUploadProductImageResponses[keyof productsUploadProductImageResponses];

export type productsDeleteProductImageData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}/images/{image_id}';
};

export type productsDeleteProductImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsDeleteProductImageError = productsDeleteProductImageErrors[keyof productsDeleteProductImageErrors];

export type productsDeleteProductImageResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type productsDeleteProductImageResponse = productsDeleteProductImageResponses[keyof productsDeleteProductImageResponses];

export type productsReorderProductImagesData = {
    body: ProductImageOrder;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}/images/order';
};

export type productsReorderProductImagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsReorderProductImagesError = productsReorderProductImagesErrors[keyof productsReorderProductImagesErrors];

export type productsReorderProductImagesResponses = {
    /**
     * Successful Response
     */
    200: ProductImagesPublic;
};

export type productsReorderProductImagesResponse = productsReorderProductImagesResponses[keyof productsReorderProductImagesResponses];

export type productsSetPrimaryProductImageData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}/images/{image_id}/primary';
};

export type productsSetPrimaryProductImageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsSetPrimaryProductImageError = productsSetPrimaryProductImageErrors[keyof productsSetPrimaryProductImageErrors];

export type productsSetPrimaryProductImageResponses = {
    /**
     * Successful Response
     */
    200: ProductImagePublic;
};

export type productsSetPrimaryProductImageResponse = productsSetPrimaryProductImageResponses[keyof productsSetPrimaryProductImageResponses];

export type productImagesReadProductImageContentData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/api/v1/product-images/{image_id}/content';
};

export type productImagesReadProductImageContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productImagesReadProductImageContentError = productImagesReadProductImageContentErrors[keyof productImagesReadProductImageContentErrors];

export type productImagesReadProductImageContentResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type productImagesReadProductImageContentResponse = productImagesReadProductImageContentResponses[keyof productImagesReadProductImageContentResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
