"""add roles and permissions

Revision ID: ae77f319a39b
Revises: b7c1f2a9d4e6
Create Date: 2026-09-26 12:49:50.218074

"""

import uuid
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae77f319a39b"
down_revision = "b7c1f2a9d4e6"
branch_labels = None
depends_on = None


# The permission catalog is snapshotted here on purpose: the migration must keep
# working even if the application catalog changes later. IDs are derived
# deterministically from the code / role slug so the seed data is stable.
_NAMESPACE = uuid.UUID("6f1b1e2a-0d6e-4c2b-9f7a-2c5b8d3e4a11")

_PERMISSIONS: list[tuple[str, str]] = [
    ("users.read", "Read any user account"),
    ("users.create", "Create user accounts"),
    ("users.update", "Update any user account"),
    ("users.delete", "Delete any user account"),
    ("users.read_self", "Read own user account"),
    ("users.update_self", "Update own user account"),
    ("users.delete_self", "Delete own user account"),
    ("items.read_own", "Read own items"),
    ("items.read_any", "Read all items"),
    ("items.create", "Create items"),
    ("items.update_own", "Update own items"),
    ("items.update_any", "Update all items"),
    ("items.delete_own", "Delete own items"),
    ("items.delete_any", "Delete all items"),
    ("roles.read", "View roles and permissions"),
    ("roles.create", "Create roles"),
    ("roles.update", "Update roles"),
    ("roles.delete", "Delete roles"),
    ("roles.assign", "Assign roles to users"),
    ("utils.send_test_email", "Send test emails"),
    ("utils.read_password_recovery_html", "Preview password recovery emails"),
]

_DEFAULT_USER_PERMISSIONS: set[str] = {
    "users.read_self",
    "users.update_self",
    "users.delete_self",
    "items.read_own",
    "items.create",
    "items.update_own",
    "items.delete_own",
}

_USER_ROLE_ID = uuid.uuid5(_NAMESPACE, "role:user")
_SUPERUSER_ROLE_ID = uuid.uuid5(_NAMESPACE, "role:superuser")

_USER_ROLE_PERMISSION_CODES = _DEFAULT_USER_PERMISSIONS
_SUPERUSER_ROLE_PERMISSION_CODES = {code for code, _ in _PERMISSIONS}


def _permission_id(code: str) -> uuid.UUID:
    return uuid.uuid5(_NAMESPACE, f"permission:{code}")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "code", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_code"), "permission", ["code"], unique=True)
    op.create_table(
        "role",
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    op.create_index(op.f("ix_role_slug"), "role", ["slug"], unique=True)
    op.create_table(
        "rolepermissionlink",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["permission.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.add_column("user", sa.Column("role_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###

    # --- Seed the permission catalog and the built-in roles -------------
    permission_table = sa.table(
        "permission",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        permission_table,
        [
            {
                "id": _permission_id(code),
                "code": code,
                "description": description,
            }
            for code, description in _PERMISSIONS
        ],
    )

    now = datetime.now(UTC)
    role_table = sa.table(
        "role",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("description", sa.String()),
        sa.column("slug", sa.String()),
        sa.column("is_system", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        role_table,
        [
            {
                "id": _USER_ROLE_ID,
                "name": "User",
                "description": "Default role for regular users",
                "slug": "user",
                "is_system": True,
                "created_at": now,
            },
            {
                "id": _SUPERUSER_ROLE_ID,
                "name": "Superuser",
                "description": "Full administrative access",
                "slug": "superuser",
                "is_system": True,
                "created_at": now,
            },
        ],
    )

    link_table = sa.table(
        "rolepermissionlink",
        sa.column("role_id", sa.Uuid()),
        sa.column("permission_id", sa.Uuid()),
    )
    links: list[dict[str, uuid.UUID]] = []
    for code in sorted(_USER_ROLE_PERMISSION_CODES):
        links.append(
            {"role_id": _USER_ROLE_ID, "permission_id": _permission_id(code)}
        )
    for code in sorted(_SUPERUSER_ROLE_PERMISSION_CODES):
        links.append(
            {"role_id": _SUPERUSER_ROLE_ID, "permission_id": _permission_id(code)}
        )
    op.bulk_insert(link_table, links)

    # --- Backfill every existing user with exactly one role -------------
    op.execute(
        sa.text(
            'UPDATE "user" SET role_id = :role_id WHERE is_superuser = true'
        ).bindparams(role_id=_SUPERUSER_ROLE_ID)
    )
    op.execute(
        sa.text(
            'UPDATE "user" SET role_id = :role_id WHERE is_superuser = false'
        ).bindparams(role_id=_USER_ROLE_ID)
    )

    # --- Enforce one role per user -------------------------------------
    op.alter_column("user", "role_id", nullable=False)
    op.create_index(op.f("ix_user_role_id"), "user", ["role_id"], unique=False)
    op.create_foreign_key(
        "user_role_id_fkey",
        "user",
        "role",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade():
    op.drop_constraint("user_role_id_fkey", "user", type_="foreignkey")
    op.drop_index(op.f("ix_user_role_id"), table_name="user")
    op.drop_column("user", "role_id")
    op.drop_table("rolepermissionlink")
    op.drop_index(op.f("ix_role_slug"), table_name="role")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_table("role")
    op.drop_index(op.f("ix_permission_code"), table_name="permission")
    op.drop_table("permission")
